# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - v1.**

jobs:

  build:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build linux amd64
      run: GOOS=linux GOARCH=amd64 go build -o ssm2ssh_linux_amd64 -v main.go

    - name: Build macos amd64
      run: GOOS=darwin GOARCH=arm64 go build -o ssm2ssh_macos_arm -v main.go
    
    - name: Compress linux amd64
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        files: |
            ./ssm2ssh_linux_amd64
        outPath: ssm2ssh_linux_amd64.tar.gz
        
    - name: Compress MacOS m1
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        files: |
            ./ssm2ssh_macos_arm
        outPath: ssm2ssh_macos_arm.tar.gz
          
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
            ssm2ssh_linux_amd64.tar.gz
            ssm2ssh_macos_arm.tar.gz
            
